apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quantum1-app
spec:
  template:
    spec:
      containers:
        - image: us.icr.io/fastapi-qiskit/quantum1:latest
          ports:
            - containerPort: 8080
