apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum1-app
  labels:
    app: quantum1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quantum1
  template:
    metadata:
      labels:
        app: quantum1
    spec:
      containers:
        - name: quantum1-container
          image: crn:v1:bluemix:public:container-registry:us-south:a/9c3be353ed4745e98a6cf06b9e9036fb::namespace:fastapi-qiskit/quantum1:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quantum1-service
spec:
  type: LoadBalancer
  selector:
    app: quantum1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080