# This GitHub Actions workflow builds a Docker image for a FastAPI application,
# pushes it to IBM Cloud Container Registry, and deploys it to IBM Code Engine.
name: Deploy to IBM Code Engine

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: us.icr.io/fastapi-qiskit/quantum1
  IBM_CLOUD_REGION: ${{ secrets.IBM_CLOUD_REGION }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_QUANTUM_API_TOKEN: ${{ secrets.IBM_QUANTUM_API_TOKEN }}
  IBM_RESOURCE_GROUP: ${{ secrets.IBM_RESOURCE_GROUP }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install IBM Cloud CLI & Plugins
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install container-registry -f
          ibmcloud plugin install code-engine -f

      - name: Authenticate with IBM Cloud
        run: |
          ibmcloud login --apikey "$IBM_CLOUD_API_KEY" -r "$IBM_CLOUD_REGION" -g "$IBM_RESOURCE_GROUP"
          ibmcloud target -g "$IBM_RESOURCE_GROUP" || true
          echo "Successfully authenticated with IBM Cloud."
      - name: Log in to IBM Cloud Container Registry
        run: |
          # Log in to the IBM Cloud Container Registry
          if ! ibmcloud cr login; then
            echo "Failed to log in to IBM Cloud Container Registry. Please check your credentials."
            exit 1
          fi
          echo "Successfully logged in to IBM Cloud Container Registry."
          

      - name: Clean local Docker image (optional)
        run: |
          if docker images | grep -q "$IMAGE_NAME"; then
            docker rmi -f $IMAGE_NAME:latest || true
            echo "Deleted existing image $IMAGE_NAME:latest"
          else
            echo "No existing image $IMAGE_NAME:latest found"
          fi

      - name: Build & Push Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Deploy to IBM Code Engine
        run: |
          ibmcloud ce project select --name quantum1-project

          # Create registry secret only if it doesn't already exist
          if ! ibmcloud ce registry get --name icr-secret > /dev/null 2>&1; then
            echo "Creating registry access secret 'icr-secret'..."
            ibmcloud ce registry create --name icr-secret --server us.icr.io --username iamapikey --password "$IBM_CLOUD_API_KEY"
          else
            echo "Registry secret 'icr-secret' already exists. Skipping creation."
          fi

          # Deploy application
          if ibmcloud ce application get --name quantum1-app > /dev/null 2>&1; then
            echo "Application 'quantum1-app' exists. Updating..."
            ibmcloud ce application update \
              --name quantum1-app \
              --image $IMAGE_NAME:latest \
              --registry-secret icr-secret \
              --env IBM_QUANTUM_API_TOKEN=$IBM_QUANTUM_API_TOKEN \
              --env IBM_RESOURCE_GROUP=$IBM_RESOURCE_GROUP \
              --command "python -m uvicorn main:app --host 0.0.0.0 --port 8080"
          else
            echo "Creating application 'quantum1-app'..."
            ibmcloud ce application create \
              --name quantum1-app \
              --image $IMAGE_NAME:latest \
              --cpu 1 \
              --memory 2G \
              --port 8080 \
              --max-scale 2 \
              --min-scale 1 \
              --registry-secret icr-secret \
              --env IBM_QUANTUM_API_TOKEN=$IBM_QUANTUM_API_TOKEN \
              --env IBM_RESOURCE_GROUP=$IBM_RESOURCE_GROUP \
              --command "python -m uvicorn main:app --host 0.0.0.0 --port 8080"
          fi
