name: Deploy to IBM Code Engine

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: us.icr.io/fastapi-qiskit/quantum1
  IBM_CLOUD_REGION: us-south

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install IBM Cloud CLI & Plugins
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install container-registry -f
          ibmcloud plugin install code-engine -f

      - name: Authenticate with IBM Cloud
        run: |
          ibmcloud login --apikey "0cSEDL8oFAOpnlzvJzwnyZZrJ8DAPn9hUSDuFWFe46uU" -r "us-south" -g "Default"
          ibmcloud cr login

      - name: Build & Push Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Deploy to Code Engine
        run: |
          ibmcloud ce project select --name quantum1-project 
          ibmcloud ce project create --name quantum1-project || true
      
          # First-time deploy (if app does not exist):
          ibmcloud ce application create --name quantum1-app --image $IMAGE_NAME:latest --cpu 1 --memory 2G --port 8080 --max-scale 2 --min-scale 1

          # If app already exists (safe to run every time):
          ibmcloud ce application update --name quantum1-app --image $IMAGE_NAME:latest
